That is because we have 

the encrypted Ansible Vault and we could not read it.